# Generated by Django 5.2.6 on 2025-09-17 02:51

from django.db import migrations, models

import core.apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=core.apps.accounts.models.user_image_path),
        ),
    ]
