# Generated by Django 5.2.6 on 2025-09-17 02:51

from django.db import migrations, models

from core.shared.storage.uploads import generate_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=generate_upload_path("users", "image")),
        ),
    ]
