# Generated by Django 5.2.6 on 2025-09-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_created_by"),
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                help_text="Hotel this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="hotels.hotel",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_hotel_admin",
            field=models.BooleanField(default=False, help_text="Whether this user is an admin for their hotel"),
        ),
    ]
