# Generated by Django 5.2.6 on 2025-09-18 05:27

from django.db import migrations, models

from core.shared.storage.uploads import generate_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="active_until",
            field=models.DateTimeField(blank=True, help_text="Hotel subscription/license expiry date", null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="cover",
            field=models.ImageField(
                blank=True, help_text="Hotel cover image", null=True, upload_to=generate_upload_path("hotels", "cover")
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Hotel logo/main image",
                null=True,
                upload_to=generate_upload_path("hotels", "image"),
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="note",
            field=models.TextField(blank=True, help_text="Internal notes about the hotel"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="social_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Social media links as JSON (e.g., {'facebook': 'url', 'instagram': 'url'})",
            ),
        ),
    ]
