# Generated by Django 5.2.6 on 2025-09-18 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_hotel_active_until_hotel_cover_hotel_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="created_by",
        ),
        migrations.AddField(
            model_name="hotel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this hotel",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_hotels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="cover",
            field=models.ImageField(
                blank=True, help_text="Hotel cover image", null=True, upload_to="uploads/hotels/covers/"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Hotel logo/main image", null=True, upload_to="uploads/hotels/images/"
            ),
        ),
    ]
