# Generated by Django 5.2.6 on 2025-09-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_remove_hotel_created_by_hotel_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="owner",
        ),
    ]
